/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ConsultarRegistroControlador;
import Modelo.Movimiento;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class ConsultarRegistro extends javax.swing.JInternalFrame {

    private ConsultarRegistroControlador consultarRegistroControlador;

    public ConsultarRegistro(List<Movimiento> movimientos) {
        initComponents();
        consultarRegistroControlador = new ConsultarRegistroControlador(movimientos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMovimientosRegistros = new javax.swing.JTable();
        txtPlacaConsultarRegistro = new javax.swing.JTextField();
        btnConsultarRegistro = new javax.swing.JButton();
        txtFechaConsultarRegistro = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultar Registro de Entrada o Salida");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setText("Consultar Registros de Vehículos");

        tableMovimientosRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Conductor", "Vehículo (Placa)", "Pago", "Destino", "Tipo de Vehículo", "Fecha", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableMovimientosRegistros);

        txtPlacaConsultarRegistro.setText("Buscar vehículo");
        txtPlacaConsultarRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPlacaConsultarRegistroKeyTyped(evt);
            }
        });

        btnConsultarRegistro.setBackground(new java.awt.Color(255, 102, 102));
        btnConsultarRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarRegistro.setText("Consultar");
        btnConsultarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarRegistroActionPerformed(evt);
            }
        });

        txtFechaConsultarRegistro.setText("dd/mm/yyyy");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setText("Ultimos Movimientos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtPlacaConsultarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFechaConsultarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarRegistro)
                .addGap(121, 121, 121))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jLabel1)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlacaConsultarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaConsultarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarRegistro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarRegistroActionPerformed

        String placa = txtPlacaConsultarRegistro.getText();
        String fecha = txtFechaConsultarRegistro.getText();

        // Valida que se ingresó al menos una de las dos condiciones de búsqueda
        if (placa.isEmpty() && fecha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa al menos una condición de búsqueda (placa o fecha).", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Consulta movimientos
        List<Movimiento> movimientosFiltrados = consultarRegistroControlador.consultarMovimientos(placa, fecha);

        // Llena la tabla con los movimientos filtrados
        DefaultTableModel model = (DefaultTableModel) tableMovimientosRegistros.getModel();
        model.setRowCount(0); // Limpia la tabla antes de llenarla con los nuevos datos

        if (movimientosFiltrados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontraron movimientos que coincidan con los criterios de búsqueda.", "Sin resultados", JOptionPane.INFORMATION_MESSAGE);
        } else {
            for (Movimiento movimiento : movimientosFiltrados) {
                model.addRow(new Object[]{
                    movimiento.getConductor(),
                    movimiento.getPlaca(),
                    movimiento.getPago(),
                    movimiento.getDestino(),
                    movimiento.getTipoVehiculo(),
                    movimiento.getFecha(),
                    movimiento.getEstado()
                });
            }
        }

    }//GEN-LAST:event_btnConsultarRegistroActionPerformed

    private void txtPlacaConsultarRegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaConsultarRegistroKeyTyped
        if (rootPaneCheckingEnabled) {

        }
    }//GEN-LAST:event_txtPlacaConsultarRegistroKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tableMovimientosRegistros;
    private javax.swing.JFormattedTextField txtFechaConsultarRegistro;
    private javax.swing.JTextField txtPlacaConsultarRegistro;
    // End of variables declaration//GEN-END:variables
}
