/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Clases.Evento;
import DAO.UsuarioDAO;
import Modelo.UsuarioModelo;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public final class UsuariosAdminVista extends javax.swing.JInternalFrame {

    Evento event = new Evento();

    /**
     * Creates new form Usuarios
     */
    public UsuariosAdminVista() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        txtUsernameUsuario = new javax.swing.JTextField();
        txtContraUsuario = new javax.swing.JTextField();
        txtIdUsuario = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableUsuario = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbxRolUser = new javax.swing.JComboBox<>();
        btnGuardarUsu = new javax.swing.JButton();
        btnActualizarUsu = new javax.swing.JButton();
        btnBajaUsu = new javax.swing.JButton();
        btnNuevoUsu = new javax.swing.JButton();
        btnActivarUsu = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registro de Usuarios");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("72", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 153, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("USUARIOS");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 280, 40));

        jLabel13.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        jLabel13.setText("NOMBRES:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 80, 20));

        jLabel14.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        jLabel14.setText("USUARIO:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 70, 20));

        jLabel15.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        jLabel15.setText("CONTRASEÑA:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 90, 20));

        jLabel16.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        jLabel16.setText("ROL:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 70, 20));

        txtNombreUsuario.setFont(new java.awt.Font("72", 0, 13)); // NOI18N
        txtNombreUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombreUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNombreUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 440, 20));

        txtUsernameUsuario.setFont(new java.awt.Font("72", 0, 13)); // NOI18N
        txtUsernameUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsernameUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtUsernameUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsernameUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtUsernameUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 140, 20));

        txtContraUsuario.setFont(new java.awt.Font("72", 0, 13)); // NOI18N
        txtContraUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtContraUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtContraUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContraUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtContraUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 140, 20));

        txtIdUsuario.setFont(new java.awt.Font("72", 0, 13)); // NOI18N
        txtIdUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtIdUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtIdUsuario.setEnabled(false);
        jPanel1.add(txtIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 20, 20));

        tableUsuario.setFont(new java.awt.Font("72", 0, 12)); // NOI18N
        tableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombres", "Usuario", "Contraseña", "Rol", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUsuarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableUsuario);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 550, 350));

        jLabel7.setFont(new java.awt.Font("72", 3, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 153, 0));
        jLabel7.setText("LISTADO DE USUARIOS REGISTRADOS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 260, -1));

        jLabel8.setFont(new java.awt.Font("72", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 153, 0));
        jLabel8.setText("REGISTRA UN NUEVO USUARIO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, 30));

        cbxRolUser.setFont(new java.awt.Font("72", 0, 13)); // NOI18N
        cbxRolUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRolUserActionPerformed(evt);
            }
        });
        jPanel1.add(cbxRolUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 140, -1));

        btnGuardarUsu.setBackground(new java.awt.Color(51, 255, 51));
        btnGuardarUsu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardarUsu.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarUsu.setText("Guardar");
        btnGuardarUsu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnGuardarUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        btnActualizarUsu.setBackground(new java.awt.Color(51, 255, 51));
        btnActualizarUsu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizarUsu.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarUsu.setText("Actualizar");
        btnActualizarUsu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnActualizarUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        btnBajaUsu.setBackground(new java.awt.Color(255, 51, 51));
        btnBajaUsu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBajaUsu.setForeground(new java.awt.Color(255, 255, 255));
        btnBajaUsu.setText("Dar de Baja");
        btnBajaUsu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnBajaUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, -1, -1));

        btnNuevoUsu.setBackground(new java.awt.Color(51, 255, 51));
        btnNuevoUsu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNuevoUsu.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoUsu.setText("Nuevo");
        btnNuevoUsu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnNuevoUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, -1, -1));

        btnActivarUsu.setBackground(new java.awt.Color(0, 153, 255));
        btnActivarUsu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActivarUsu.setForeground(new java.awt.Color(255, 255, 255));
        btnActivarUsu.setText("Activar Usuario");
        btnActivarUsu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnActivarUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 590, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void txtNombreUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreUsuarioKeyTyped
        // TODO add your handling code here:
        event.textKeyPress(evt);
    }//GEN-LAST:event_txtNombreUsuarioKeyTyped

    private void txtUsernameUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameUsuarioKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtUsernameUsuarioKeyTyped

    private void txtContraUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraUsuarioKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtContraUsuarioKeyTyped

    private void tableUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUsuarioMouseClicked
        int fila = tableUsuario.rowAtPoint(evt.getPoint());

        txtIdUsuario.setText(tableUsuario.getValueAt(fila, 0).toString());
        txtNombreUsuario.setText(tableUsuario.getValueAt(fila, 1).toString());
        txtUsernameUsuario.setText(tableUsuario.getValueAt(fila, 2).toString());
        txtContraUsuario.setText(tableUsuario.getValueAt(fila, 3).toString());
        cbxRolUser.setSelectedItem(tableUsuario.getValueAt(fila, 4).toString());// Falta Implementar. si es 1 es admin, 2 vigilante de garita
        
        
    }//GEN-LAST:event_tableUsuarioMouseClicked

    private void cbxRolUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRolUserActionPerformed
        // TODO add your handling code here:ss
    }//GEN-LAST:event_cbxRolUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActivarUsu;
    public javax.swing.JButton btnActualizarUsu;
    public javax.swing.JButton btnBajaUsu;
    public javax.swing.JButton btnGuardarUsu;
    public javax.swing.JButton btnNuevoUsu;
    public javax.swing.JComboBox<String> cbxRolUser;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tableUsuario;
    public javax.swing.JTextField txtContraUsuario;
    public javax.swing.JTextField txtIdUsuario;
    public javax.swing.JTextField txtNombreUsuario;
    public javax.swing.JTextField txtUsernameUsuario;
    // End of variables declaration//GEN-END:variables
}
